- src/data/country-data.php
- src/models/Team.php
The scoreboard first_capture always return the first team in the order of team name instead of the order of captured time.
> first_capture does not return the correct result

- README.md
- extra/lib.sh
- extra/provision.sh
This PR:
- makes the provision script exit immediately when any command returns a non-zero exit code
- removes dev packages like emacs and mycli from the prod builds
- pulls out the password creation functionality into it's own function, and updates the README with this info
I'm still doing some more robust testing, will let you know when this is OK to merge.
> Provision script improvements, and ability to set password from the command line

- extra/provision.sh
Installing language-pack failed while provisioning because apt wasn't updated at this point.
```
==> default: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/language-pack-en-base/language-pack-en-base_14.04+20140707_all.deb  404  Not Found [IP: 91.189.88.152 80]
```
> Provisioning: Install language-pack-en after apt-get update

- src/data/command-line.php
- src/data/map-data.php
- src/static/svg/map/world.php
Instead of doing a SELECT statement for every single country, we just do two queries, one to get all levels, and one to get active countries.
> Reduce the number of SQL queries when getting map data

- package.json
There was a problem with DropKick and Cross Site Scripting, due to the element being assigned the text instead of the encoded innerHTML. See https://github.com/Robdel12/DropKick/pull/338 for the fix.
> DropKick version bump to fix XSS

- .dockerignore
- Dockerfile
- README.md
- extra/lib.sh
- extra/provision.sh
- extra/service_startup.sh
I've added some files in extra/ to make dockerizing more easier, and updated README as well.
Would you please have a look at it? Thanks!
> I've finished dockerizing fbctf both in dev and prod mode :D

- extra/lib.sh
Latest HHVM package (3.15) for Ubuntu 14.04/16.04 is broken so this mitigates the impact by installing the last good package (3.14.5).
Issue in HHVM already created: https://github.com/facebook/hhvm/issues/7333
> Mitigation for broken HHVM 3.15 package

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/inc/gameboard/modules/game-clock.php
- src/models/Control.php
- src/static/css/scss/_gameboard.scss
- src/static/js/clock.js
As requested in #78 the possibility to select arbitrary game duration is implemented:
TODO: if a duration longer than 99 hours is selected, then the Gameclock overlaps:
> Configuration option for arbitrary game duration added

- src/scripts/bases.php
- src/scripts/progressive.php
Runs fine from terminal, but:
```
fredemmott-mbp1:extra fredemmott$ curl -kI https://localhost/scripts/bases.php
HTTP/1.1 405 Method Not Allowed
Server: nginx
Date: Wed, 05 Oct 2016 16:49:58 GMT
Content-Type: text/html
Connection: keep-alive
X-Powered-By: HHVM/3.14.5
Vary: Accept-Encoding
```
> Disallow running scripts from web

- src/data/controller.php
Because it can (and does) quite readily more than double the size of the data being sent, and is completely unnecessary.
> Don't pretty print DataController JSON data

- src/controllers/ajax/GameAjaxController.php
This part of the code still allows correct answer submissions on inactive levels, which can lead to weird UI states. This commit prevents that behavior. I also made `$level_id` and `$answer` into variables to improve readability of this part.
> Forbid correct answer submissions on inactive levels

- src/models/Country.php
- src/models/Level.php
Levels get the country assigned by iso_code, since the names are all going through each translation, fixes #262
> Fix for import/export levels, since country names are not present

- extra/provision.sh
When provisioning, ```npm install``` was missing a sudo, so there was an error thrown out because some packages were not installed. Fix for #224
> Fixing missing sudo when provisioning

- database/schema.sql
- database/test_schema.sql
- src/Router.php
- src/SessionUtils.php
- src/controllers/AdminController.php
- src/controllers/IndexController.php
- src/controllers/ajax/AdminAjaxController.php
- src/controllers/ajax/GameAjaxController.php
- src/controllers/modals/ScoreboardModalController.php
- src/data/command-line.php
- src/data/country-data.php
- src/data/leaderboard.php
- src/data/map-data.php
- src/data/scores.php
- src/data/teams.php
- src/inc/gameboard/modules/leaderboard-viewmode.php
- src/inc/gameboard/modules/leaderboard.php
- src/inc/gameboard/modules/teams.php
- src/language/lang_bp.php
- src/language/lang_cat.php
- src/language/lang_en.php
- src/language/lang_es.php
- src/language/lang_hu.php
- src/models/Level.php
- src/models/MultiTeam.php
- src/models/Session.php
- src/models/Team.php
- src/static/svg/map/world.php
- tests/models/MultiTeamTest.php
* Creation of the MultiTeam class, extending the Team class and overloading certain class methods to combine database queries and retain data retrieved from the database for subsequent usage.  Overall, this class dramatically reduces the queries to the teams table.  Specifically, this ensures queries are only called once per page request.
* MultiTeam::genTeam() replaces the Team instantiation with a method that utilizes the teams database results stored within the Multi::Team class.  All Team::genTeam() calls have been updated to utilize MultiTeam::genTeam().  This reduces the number of queries when building multiple team objects from 1(n) to 1.
* MultiTeam::genLeaderboard() replaces the method to retrieve a sorted array of Team objects used for scoring displays.  Previously this would …
> Major Reduction of MySQL Queries

- src/controllers/IndexController.php
The current XHP results in the literal string {tr('ERROR')} ending up in the output.  XHP doesn't quote attributes with "".
> Fix formatting of error page glitching.

- src/static/js/fb-ctf.js
The selector `#register_names` doesn't seem to be in the DOM.
This change replaces that check with one that checks for the value of the hidden input named `action`. If that value is `register_names` we make sure to collect the names and add them to the AJAX response to the server.
Fixes #86
> Use the correct CSS selector to find out if names are required

- src/models/Team.php
genFirstCapture would throw an error due to the query return no rows, but the return statement requires one row (due to the [0] ). This would happen when a disabled or invisible user was had the first (but not only) capture. I used a second sub-query to fix this as the rest of this code base appears to favor sub-queries instead of joins.
> Fix index error in genFirstCapture in Teams.php

- src/controllers/ajax/GameAjaxController.php
- src/models/Model.php
- src/models/MultiTeam.php
- src/models/ScoreLog.php
- src/models/Team.php
- Moved setMCRecords(), getMCRecords(), and invalidateMCRecords() to the Model class.  These methods will be utilized in any Model class in which Memcached is implemented.
- MC_KEY, MC_EXPIRE, and MC_KEYS have been converted to protected static properties on the Model class, which can then be overloaded by the children classes.  These static parent properties allow each class to define the relevant Memcached settings needed.
- MC_EXPIRE now defaults to 0 (indefinite), this can be overridden by a child class if the need arises.
- The Memcached for MultiTeam and ScoreLog are invalidated on demand.  This invalidation takes place when teams are modified, created, or deleted and when scoring events are triggered.
- Fixed an issue where the full class cache wasn't being invalidated if no …
> Updated Memcached Implementation

- src/models/Level.php
- tests/_files/seed.xml
- tests/models/LevelTest.php
* Flags have now been made case sensitivity.  Previously the case was ignored when checking the correctness of a flag answer.
* Added a Unit Test to ensure the flag was only counted as correct when the case matches.
> Flag Case Sensitivity Update

- config
- src/inc/gameboard/modules/announcements.php
- src/static/css/scss/_gameboard.scss
Announcements did not have a proper format and they ended up as clutter and not really helpful. Issue is #213. Now they have the timestamp and separation.
> Announcements have now timestamp and are less clutered

- src/language/lang_ru.php
This adds some kind of Russian translation. The thing is, there's still some work to be done because Russian language is not that flexible and it's a hit and miss trying to translate one or two words without a context. It also distinguishes between a verb and a noun, as well as contains cases and conjugations. So this needs to be polished by other community members who can launch the platform and play with it, fixing misused translations. Although I didn't have any similar program translating experience it seems to me that this is not the best way to provide localization because it's so error-prone. However, I don't have any alternative solution to suggest.
> Add Russian translation

- extra/provision.sh
Fixes issue #329 by installing dependencies.
Which version of python do we need, 2 or 3? This works with both, but I want to only include what we need.
Reviewers: @javuto
> Install correct dependencies in dev

- src/controllers/AdminController.php
* Combined multiple sequential awaits based on the documentation provided here:  https://docs.hhvm.com/hack/async/awaitables#awaiting__batching-awaitables
* The combined configuration requests provide minor performance improvements, due to the existing efficient usage of Memcached.
* The combined Scoring Logs requests provides a clear performance improvement, especially when there is a large amount of scoring activity within the logs.
> Combined Asynchronous Awaitables

- src/models/MultiTeam.php
- src/models/ScoreLog.php
* Updated the usage of Memcached throughout the MultiTeam and ScoreLog classes (the only two classes utilizing the new Memcached implementation at the time) to resolve a race condition. It was possible that the cache existence could be verified and then the cache is invalidated before the cache is retrieved and utilized. Now the cache is retrieved and utilized without a second request. This resolves the race condition.
* Updated Hack/HHVM Type Checking. Removed all instance of HH_IGNORE_ERROR and updated to use invariant to confirm the type and nullability. Combined both the type and null checks into a single invariant to cleanup the code.
* Updated some code styling based on discussions on the pending PRs (relevant to these classes, and the Memcached implementation).
* This race …
> Fixed Memcached Race Condition

- src/models/Attachment.php
* Updated Attachment::genAllAttachments() and Attachment::genHasAttachment() to utilize Memcached.  Previously the methods were calling 1(n) queries per level.  Now the queries have been consolidated to a single query each, and the data is stored in Memcached.  The queries will now only run after invalidation due to an attachment being altered.
> Added Memcached Implementation to Attachment

- src/controllers/ajax/GameAjaxController.php
- src/models/HintLog.php
* Updated HintLog::genPreviousHint() to utilize Memcached.  Previously the method was calling 2(n) queries per level.  Now the query has been consolidated to a single query, and the data is stored in Memcached.  The single query will now only run after invalidation due to a hint being used.
* Updated the GameAjaxController class to invalidate the caches for scoring (the MultiTeam class) on hint usage.
* Updated GameAjaxController class to remove the MultiTeam and ScoreLog cache invalidations on a valid scoring event, these are now handled internally within the relevant classes.  This change is dependent on PR: facebook/fbctf#339
> Added Memcached Implementation to HintLog

- src/models/MultiTeam.php
* Updated MultiTeam::genFirstCapture() to ensure the Gameboard doesn't break if the first team to capture a level is deleted.
> Fixed Gameboard Breakage on Team Delete

- src/models/Link.php
* Updated Link::genAllLinks() to utilize Memcached.  Previously the method was calling 1(n) query per level.  Now the queries have been consolidated to a single query, and the data is stored in Memcached.  The queries will now only run after invalidation due to a link being altered.
> Added Memcached Implementation to Link

- src/models/Category.php
* Updated the Category::genAllCategories() to utilize Memcached.  Previously this method only ran a single query but it happened frequently.  The query results are now cached and invalidated when Categories are altered.
> Added Memcached Implementation to Category

- src/models/Progressive.php
* Updated Progressive::genProgressiveGameboard() to utilize Memcached.  Previously the method was calling 1(n) query per team.  Now the queries have been consolidated to a single query, and the data is stored in Memcached.  The queries will now only run after invalidation due to a change to the progressive log.
* Updated Progressive::genCount() to store the results in Memcached.  The cache is updated when the iteration changes, based on an update to the progressive log.
* The restructuring of this code has the benefit of fixing the graphic score display on the Scoreboard.
> Added Memcached Implementation to Progressive

- src/Router.php
- src/models/Session.php
- tests/models/SessionTest.php
* Sessions are still stored within the database; however, sessions are now replicated into Memcached.  By adding a Memcached layer on-top of Sessions, most session-related functions no longer require a query against the database, dramatically reducing the queries and improving performance.
* All session related functions are redundant; if the data is not found within the cache, but does exist in the database, it will be retrieved from the database and stored in the cache.  The redundancy ensures that failures or thrashing of Memcached do not invalidate valid sessions.
* Sessions are stored back to the database at the same frequently as they were prior to this update.  Specifically, the session is written to the database on each full-page load.
* The session cache is updated on every …
> Added Memcached Implementation to Sessions

- src/controllers/AdminController.php
- src/models/Control.php
- src/models/Country.php
- src/models/Level.php
- src/models/ScoreLog.php
- src/models/Team.php
* Updated Memcached Implementation on Country, ScoreLog, and Team.
* Updated Level::genWhoUses(), Level::genCheckStatus(), Level::genCheckBase() to reduce queries and utilize Memcached.  Previously each method was calling one query per country.  Now the methods have been updated to consolidate the various queries into a single query for all levels.  The resulting data is stored in Memcached and queries only runs after cache invalidation.
* Updated Level::genAllLevels(), Level::genAllActiveLevels(), and Level::genAllActiveBases() to utilize Memcached.  These methods were previously only calling a single query each, but they are used often on the Gameboard updates.
* Updated Level::genAllTypeLevels() to utilize Memcached.  This method was previously performing a single query per level type, …
> Added Memcached Implementation to Level and Control

- Vagrantfile
- extra/provision.sh
Mitigation for the ```502 Bad Gateway``` problem (https://github.com/facebook/fbctf/issues/234) when restarting the FBCTF machine, making HHVM Repo Authoritative mode optional.
Also, providing the environment variable ```FBCTF_PROVISION_ARGS```, the arguments to provision can be modified for the vagrant machine.
> HHVM Repo Authoritative mode optional and change provision arguments

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/controllers/IndexController.php
- src/controllers/ajax/IndexAjaxController.php
- src/language/lang_basque.php
- src/language/lang_cat.php
- src/language/lang_en.php
- src/language/lang_es.php
- src/language/lang_hu.php
- src/models/Team.php
- src/static/js/admin.js
This change enables LDAP support for registration and login (Issue #126). The basic workflow is as follows.
1. The admin user enables LDAP and configures the following options.
- LDAP Server
- LDAP Port
- LDAP Domain Suffix for Logging in (such as '@domain.com')
2. The player registers by using LDAP username as the team name, and using LDAP credentials. On successful validation of credentials, the team is created locally with a random local password to avoid compromise of LDAP password if the server's database is compromised at a later stage.
3. The player logs in and plays the game using LDAP username as the team name and using LDAP credentials. Password is verified against LDAP server instead of local database.
The registration and login workflows remain the same as before, if LDAP is …
> LDAP Support For Registration and Login

- src/models/Configuration.php
- src/models/Session.php
- src/models/Team.php
* The new Session::getUnprotectedSessions() method returns all non-admin sessions and is now used in conjunction with the new Session::genDeleteAllUnprotected() method.  When an admin disables all teams, all non-administrative sessions are deleted and invalidated.
* Session::genDeleteByTeam is called to delete and invalidate team sessions on password update, team status toggle, and team deletion.
* Added condition to Configuration::genUpdate() to delete and invalidate all user sessions when an administrator disables login via the ‘login off’ admin toggle.
* The SQL limit was removed from Session::genDeleteByTeam() delete query. This resolves the issue where only one team session is being deleted after a team deletion.
* Updated the Team class to add session invalidation when team settings …
> Updated Session Invalidation

- src/controllers/AdminController.php
- src/controllers/modals/ActionModalController.php
- src/models/Team.php
- src/static/js/admin.js
* Added a confirmation dialog (modal) when an admin deletes a team.
* Ensured all team data is properly deleted from the relevant database tables.  The team data is now deleted from the team, registration_tokes, scores_log, hints_log, and failures_log tables.
> Added Cascading Delete for Team Deletion

- extra/provision.sh
There is a typo in the usage text which is critical to certificate renewal.
> Typo provision.sh

- src/models/Session.php
* Sessions will now properly function when Memcached fails or is not present.  When Memcached is in use the added benefits, including more granular user tracking, will be enabled.  If Memcached is not present, the sessions will be directly handled by the database.
* This resolves issues #373 and #375
> Updated Session Caching

- extra/service_startup.sh
* Ensure Memcached is automatically started in Docker containers.  Memcached is not required but dramatically improves performance.
* This resolves issues #373 and #375
> Autostart Memcached in Docker

- src/controllers/AdminController.php
Throw this error:
> [Sun Jan 22 20:18:19 2017] [hphp] [13528:7f3ebf7ff700:4:000001] [] \nNotice: Undefined variable: genCheckStatus in /var/www/fbctf/src/controllers/AdminController.php on line 2702
> 
> [Sun Jan 22 20:18:19 2017] [hphp] [13528:7f3ebf7ff700:4:000002] [] \nFatal error: Function name must be a string in /var/www/fbctf/src/controllers/AdminController.php on line 2702
> Fix fail error

- src/controllers/IndexController.php
- src/controllers/ajax/IndexAjaxController.php
* Added an "Admin Login" button to the disabled login page.
* Only valid admin accounts can login when team login is disabled.
* Provide notice to users that only an admin can login at the time (when team login is disabled).
> Allow Admin Login When Team Login Disabled

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/controllers/IndexController.php
- src/models/Control.php
- src/static/js/admin.js
* Allow an administrator to set the start and end date/time for the game.
* If the game has not started and is set to start in the future the "countdown" page will display the date of the upcoming game and the time remaining until the game begins.
* If the game is currently running the "countdown" page will display "In Progress."
* If no game is schedule the "countdown" page will display the default of "Soon."
* The administrator can change the end date/time of the game at any point and the various timers/displays will update appropriately.
* Configuration table within the database has been updated to define the data type found in the "next_game" field.
* JavaScript have been updated to handle the submission and processing of the new schedule fields on the admin Configuration page.
* …
> Added Game Schedule Functionality

- src/controllers/AdminController.php
- src/controllers/ajax/AdminAjaxController.php
- src/controllers/modals/ActionModalController.php
- src/models/Control.php
- src/models/MultiTeam.php
- src/static/js/admin.js
* Allow administrators to flush Memcached directly from the interface.  Flushing Memcached is required anytime data is manually manipulated within the database, additionally, if there is any caching issue, flushing Memcached is recommended.  The cache will rebuild after a flush without any additional action required by the user.
* Allow administrators to reset the database.  Resetting the database is useful when wanting to wipe all data from the application. Additionally, the process can be used to upgrade to the latest database schema.  Resetting the database will remove all current data (except admin users) and flush the data from the cache.  Administrative users will remain after a database reset.
* Added new "Utilities" line to the admin Control page.  Both the Flush Memcached and …
> Flush Memcached and Reset Database Admin Utilities

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/controllers/IndexController.php
- src/controllers/ajax/IndexAjaxController.php
- src/language/lang_en.php
- src/models/Configuration.php
- src/models/Logo.php
- src/static/js/admin.js
- src/static/js/index.js
- src/xhp/Fbbranding.php
- tests/models/PasswordTypesTest.php
Strongs passwords now can be enforced, with a configuration radio button and a dropdown select to pick how strong the password will be:
The registration window will look like this when the chosen password is not strong enough:
> Registration enforcing strong passwords

- database/schema.sql
- src/controllers/AdminController.php
- src/controllers/Controller.php
- src/controllers/GameboardController.php
- src/controllers/IndexController.php
- src/controllers/ViewModeController.php
- src/controllers/ajax/AdminAjaxController.php
- src/language/lang_en.php
- src/language/lang_es.php
- src/models/Logo.php
- src/static/css/scss/_admin.scss
- src/static/css/scss/_icons.scss
- src/static/js/admin.js
- src/static/js/fb-ctf.js
- src/xhp/Custombranding.php
- src/xhp/Fbbranding.php
This pull request implements the customization for brand, which has been requested in https://github.com/facebook/fbctf/issues/203 and https://github.com/facebook/fbctf/issues/93. It allows to customize the logo and the text underneath. By default it is turned off and the displayed text is "Powered By Facebook", with the small FB logo. The new settings are under the "Branding" section:
When enabling the option for a "Custom Logo", the logo can be uploaded, and it will be displayed. The text can be edited at any moment:
Anywhere in the game where the branding is displayed, will have the custom view (Gameboard, Registration, View Mode):
> Custom branding for icon and text

- package.json
* This resolves a current build error #455.
* bxslider was updated from 4.2.6 to 4.2.7 on February 14th.  Previously FBCTF allowed for a near match to 4.2.6.  However, FBCTF fails to build with 4.2.7.  During the installation process grunt failed to build the browserify javascript.
> Require bxslider version 4.2.6 (Fixes #455)

- database/schema.sql
- database/test_schema.sql
- src/Router.php
- src/controllers/AdminController.php
- src/models/Control.php
- src/scripts/autorun.php
* Games will automatically start and stop at their scheduled times.  Administrators can still manually start or stop a game regardless of the configured schedule.
* Both Control::genAutoBegin() and Control::genAutoEnd() were added to check the current time against the scheduled start or stop time and perform the relevant action (Control::genBegin or Control::getEnd).
* Control::genAutoRun() checks the current game status and determine if the game should be starting or ending, calling the appropriate function (Control::genAutoBegin or Control::getAutoEnd) and is exclusively used in the new autorun.php script.
* Control::genRunAutoRunScript() runs the new autorun.php script, ensuring the script is not already running before starting a new copy.
* The Router class was updated to include a …
> Automated Game Start and Stop

- src/Db.php
- src/controllers/AdminController.php
- src/controllers/ajax/AdminAjaxController.php
- src/controllers/importers/BinaryImporterController.php
- src/controllers/modals/ActionModalController.php
- src/models/Attachment.php
- src/models/Control.php
- src/models/Level.php
- src/static/js/admin.js
* Attachments can now be exported and imported.  On export, attachments are downloaded into a Tar Gzip and securely extracted on import.
* Links and Attachments data is now provided within the Levels export.  Users must import both the Level data and the Attachment files to restore the levels with attachments.
* A database restore option has been added which utilizes the backed up database content.  This overwrites all data in the database.
* The Control page has been reorganized to align the various functionality better.
* Memcached flushing has been added to all relevant data imports.
* Error handling has been added to the various import functions.
> Attachments and Links Import/Export, Database Restore, and Control Cleanup

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/data/livesync.php
- src/scripts/liveimport.php
* Live Sync API is now disabled by default.
* Admins can enable or disable the Live Sync API from the Administration Configuration page.
* Live Sync API now has an optional 'Auth Key.'  When the auth key is set, anyone attempting to pull from the API must supply the auth key value in their request.  Without the auth key, no data is provided by the Live Sync API endpoint.
* When using the Auth Key, it must be added as a parameter to the URL value in the `liveimport` script: ```?auth=XXXXX```
* Example (with an auth key of `1234567890`:
* `hhvm -vRepo.Central.Path=/var/run/hhvm/.hhvm.hhbc_liveimport /var/www/fbctf/src/scripts/liveimport.php --url 'https://10.10.10.101/data/livesync.php?auth=1234567890'`
* Note:  When using the Auth Key you should use a secure key.
* The `livesync` API …
> Updated LiveSync Security

- extra/lib.sh
Forcing Grunt to continue as it is not correctly detecting node_modules in the folder.  
#499 & #500
> Temp fix for issue 499 & 500 - Force Grunt to continue

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/inc/gameboard/modules/activity.php
- src/models/ActivityLog.php
- src/models/Announcement.php
- src/models/Control.php
- src/models/Country.php
- src/models/Level.php
- src/models/ScoreLog.php
- src/models/Team.php
- tests/_files/seed.xml
- tests/models/ConfigurationTest.php
- tests/models/LevelTest.php
* Dynamically generate activity log and store in the database. Activity log table stores the object type and identifier, so the log is up to date even if some portion of the object has changed (i.e., name).
* Optionally, allow for game related activites to be automatically announced through the announcements area.
* Added table "activity_log" to database.
* Added column "auto_announce" into database configuration table.
* Added auto announcement toggle in admin panel.
* Added auto announcement and activity logging for:
* Game Start, Pause, Resume, and End
* Levels being Added, Updated, Enabled, Disabled
* Added activity logging for levels being captured.
* Added ActivityLog class:
* genCaptureLog() - Stores level capture event in activity log
* genCreateGameActionLog() - Stores a change …
> Auto Announcements and Activity Log Expansion

- src/models/Level.php
* Added backward compatibility to the Level import process for exported files prior to PR #451 
* Levels exported after PR #451 contain Links and Attachments, however prior to PR #451 they did not.  The import code will now import levels even if the import file doesn't contain Links or Attachments.
> Level Import Fix

- src/controllers/AdminController.php
* Renamed "Game Controls" to "Announcement Controls" on the administrative Announcement page.
> Announcements Controls Rename

- src/models/MultiTeam.php
* Before a game begins, or before any scores are captured, the Memcached is empty for multiple scoring values. This results in continual hits to the database.
* Scores are now cached at zero until the first capture is obtained.   This dramatically reduces the number of queries performed and the load on the server.
> Set Default Scoring Cache Values

- database/logos.sql
- src/models/Logo.php
- src/models/Team.php
* Functionality prevents users from utilizing the same logo as another user/team or one already in use.
* Users now are provided the option of selecting a unique, or unused logo.
* When a logo is selected the logo is marked as used.
* When a logo is removed from a team (through team deletion, logo change, or otherwise) the logo is readded to the rotation for available logos.
* When a team is imported their logo is set to used.
* Database schema changed to set the default for all logos to unused. The scheme update also sets the admin logo to used.
> Unique Logos Per Team

- database/schema.sql
- database/test_schema.sql
- src/controllers/AdminController.php
- src/controllers/Controller.php
- src/controllers/GameboardController.php
- src/controllers/IndexController.php
- src/controllers/ViewModeController.php
* Added "Custom Organization," editable within the administrative interface. The organization will display the system name (i.e., "Custom CTF") in all relevant locations including the page titles.
* Custom Text has been renamed to "Custom Byline."
* The custom organization value will also be used for the welcome message on the landing page.
* Database updated to support the new customization options.
> Custom Branding Update

- extra/run_tests.sh
* If `settings.ini` exists it will not be copied to `settings.ini.bak` during the testing process (/extra/run_tests.sh).
* After the tests complete, if the backup file exists it will restore the file.
> Backup and Restore Settings.ini on Tests

- extra/lib.sh
- extra/provision.sh
- package.json
* Downgraded Dropkick.js to version 2.1.10.  The project originally was built using 2.1.10 and specified a near version in the 2.x.x release family.  On August 27th 2017 Dropkick.js released version 2.2.0 which is incompatible with ES6 specs. The incompatibility with the new release of Dropkick.js caused the provisioning of the platform to fail.
* Moved the installation process for Node.js to a function within `lib.sh`.  This change streamlines the provision script.
* Removed the installation of `wget` from provisioning.  `wget` is no longer used within the project and is therefore unneeded.
* Updated the `dl()` download function within the provision script to use `curl` exclusively, with retry options.  The retry options are set to 5 retries with a 15-second delay between retries.  The …
> Downgraded DropkickJS and Streamlined Provision for NodeJS/Downloads (Fixes: #554)

- .travis.yml
- extra/run_tests.sh
* Travis-CI now builds a docker image and uses the docker image for build testing.
* Split docker build, docker run, and the docker execution of `run_tests.sh` into separate steps.
* Added a service status check to `run_tests.sh` to ensure services are running or wait until they are.  The service test process will not directly return any error status; instead, the process will wait (up to 10 times, 10 seconds each) for the services to come online before finally failing with an error or continuing if everything is ready.
* This change removes our dependency on Travis-provided images and allows us to move away from Ubuntu 14.04 when ready.
> Travis-CI to use Docker

- src/static/js/fb-ctf.js
Hello, having lots of users playing the game some times generates errors on the backend side, or some latency. 
Last year we had some issues because our server was overloaded. When a user sent a request it took too long, and the frontend sent new ones without waiting for the first one (creating more issues on the server).
This PR will prevent two things:
* If a request was sent, don't create another one until the first one has finished.
* If a request fails, wait one extra "round" before sending new ones.
All suggestions are welcome, I'm not a frontender so I'm sure this can be improved.
> Prevent extra frontend requests on errors

- extra/lib.sh
When running `docker-compose build nginx` in production mode, the following error is raised:
```bash
[+] Installing nginx and certificates
[+] Deploying certificates
Generating a 2048 bit RSA private key
..............+++
...........+++
writing new private key to '/etc/nginx/certs/fbctf.key'
-----
Signature ok
subject=/O=Facebook CTF
Getting Private key
/root/extra/lib.sh: line 131: /root/tmp/certbot.sh: No such file or directory
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c ./extra/provision.sh -m $MODE -c $TYPE -k $KEY -C $CRT -D $DOMAIN -e $EMAIL -s `pwd` --docker --multiple-servers --server-type nginx --hhvm-server hhvm' returned a non-zero code: 1
```
When we ensure that the `/root/tmp` directory exists before writing the `certbot.sh` script into it, everything …
> Ensure /root/tmp exists before writing there

- .gitignore
- extra/nginx/nginx.conf
- extra/provision.sh
- src/controllers/AdminController.php
- src/data/attachment.php
- src/data/attachments/deleted/index.php
- src/data/attachments/index.php
- src/data/country-data.php
- src/models/Attachment.php
- src/models/Control.php
- src/static/js/fb-ctf.js
* Attachments have been moved out of a web accessible direcotry (`/var/www/fbctf/src/data/`) and now reside in `/var/www/fbctf/attachments`.
* Attachment downloads are now handled by an endpoint in `/data`: `attachment.php`.
* All links to attachments now refer to the correct `attachment.php` endpoint location.
* The `tar` command within the Attachment Import function now sets the mode to 600 at time of extraction.
* The Attachment Import functionality will no longer change or attempt to change permissions on the current or parent directories.
* The Attachment Import functionality will no longer change permissions on any directories, though subdirectories are not supported.
* Attachment filenames will no longer be altered, excluding the inclusion of the file hash.
* The provision script …
> Attachment Security Update

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
**What is the change?**
Adding a document linking to the Facebook Open Source Code of Conduct,
for visibility and to meet GitHub community standards.
**Why make this change?**
Facebook Open Source provides a Code of Conduct statement for all
projects to follow.
Exposing the COC via a separate markdown file is a standard being
promoted by GitHub via the Community Profile in order to meet their Open
Source Guide's recommended community standards.
**Issue**
internal task t23481323
> Code of Conduct

- src/data/attachment.php
When downloading an attachment, the byte length of the file is appended, see issue #617.
> Fix attachments code
