facebook/fbctf

.travis.yml, extra/lib.sh, extra/provision.sh, extra/run_tests.sh
- Adding tests running on travis in every commit and PR. 
- Removing coverage results from test run until issue https://github.com/facebook/hhvm/issues/1589 is resolved 
- Rearranging of hhvm install in provision script to make sure 3.13 is installed in every machine.
=> Adding tests script to travis.yml

README.md, extra/lib.sh
=> Changed 2 apt-get installs to package call.

src/Router.php, src/controllers/AdminController.php, src/controllers/GameboardController.php, src/controllers/IndexController.php, src/controllers/ajax/AdminAjaxController.php, src/controllers/ajax/GameAjaxController.php, src/controllers/ajax/IndexAjaxController.php
Without this line, all the actions through the admin ajax controller can be performed by anyone. This is not good.
=> Enforcing admin privileges in the Ajax controller

.travis.yml, README.md, extra/lib.sh, extra/provision.sh, extra/unison.sh
For production deployments, you can now use letsencrypt to create certificates. It uses certbot
=> Production deployment using letsencrypt certs

README.md
Better documentation about types of certificates to use and examples of commands.
=> Adding information about certificates and example commands

extra/lib.sh, extra/provision.sh
With the latest changes in the options I forgot to update the getopt string.
=> Fixed options for getopt

src/models/Level.php
There was a race condition which would allow people to score twice by submitting two requests concurrently. Teams could also request two hints even if they only had points for one hint, because of this race condition. This PR should fix both issues.
=> Fixed scoring race condition

extra/lib.sh, extra/provision.sh
=> Add update flag to provision script

src/controllers/AdminController.php
Changed enable and disable to enabled and disabled.
=> # 77 Enabled/Disabled

Dockerfile, extra/service_startup.sh
fix https://github.com/facebook/fbctf/issues/209
=> fix https://github.com/facebook/fbctf/issues/209

src/static/js/admin.js, src/static/js/index.js, src/static/js/plugins.js
Lint error in plugins.js
51:9  error  Move function declaration to function body root  no-inner-declarations
UglifyJS error on ES6 Object Initializer spec
UglifyJS doesn't support objects that can be created with computed keys
=> Patch for `grunt release` failure

extra/provision.sh
=> Warn when the machine has <1GB of RAM.

Dockerfile, extra/lib.sh
1. Fix https://github.com/facebook/fbctf/issues/229
2. Merge https://github.com/facebook/fbctf/pull/191, since the PR should be no problem including docker provisioning, and the developer doesn't pong for a while.
Thanks :)
=> Fix #229 and Merge #191

src/language/lang_es.php
Added spanish language to fbctf
=> Added spanish translation

src/language/lang_basque.php
Referencing #251 
Added Basque translation of fbctf.
=> Added Basque translation.

src/static/js/fb-ctf.js, src/static/js/filter.js, src/static/js/widget.js
Implementation for #241, this pull request adds a new javascript module, ```filter.js```, that persist the values of the filters module in a set of cookies.
=> Persistent filters on refresh, added new cookies

README.md, extra/lib.sh, extra/provision.sh
This PR will improve how the update happens for a currently installed platform, using the ```provision.sh``` script. Relevant to https://github.com/facebook/fbctf/issues/277
=> Improve the update process

extra/provision.sh
It will help clarify situations like https://github.com/facebook/fbctf/issues/275
=> Display vagrant IP address only in vagrant environments

extra/run_tests.sh, src/language/language.php
This is going to fail until I fix the reason why the tests were failing. Tests were silently failing before (#227).
=> Fix tests.

database/test_schema.sql, src/controllers/AdminController.php, src/controllers/importers/JSONImporterController.php, src/models/Control.php, src/models/Logo.php, tests/_files/seed.xml, tests/models/ConfigurationTest.php
Fix for test script related with PR #232  - updated some testcase, test_schema, test data
Fix for game import game - missing input element in AdminController 
- add checking using "instanceof KeyedContainer"
=> Test and import game fix

extra/lib.sh, extra/provision.sh
=> Avoid multiple entry in /etc/apt/sources.list when re-install

src/language/lang_it.php
=> Added italian translation

src/language/lang_de.php
The first version of the german translation. Completed issue #236.
=> Add german translation (#236)

extra/load-tester.py, test.sh
This is a rough script I threw together to load test a server
[skip ci]
=> Added load-testing script

src/language/lang_fr.php
The first version of the french translation for issue #235.
=> Add french translation

src/language/lang_tr.php
=> Add Turkish translation

src/language/lang_id.php
=> Added Indonesian Translation

src/models/Announcement.php
* Updated the Memcached implementation within the Announcement class to bring it inline with the other Memcached code.
=> Refactored Announcement Memcached Implementation

extra/provision.sh
Mitigation for NPM installation issues, due to an old version of NPM. More information here: https://github.com/npm/npm/issues/14610
=> Fix for npm problem

src/inc/gameboard/listview.php
* Updated ListviewController::genRender() to pass the Entity (Country) ID instead of the Level ID to Country::gen().
=> Fixed Issue #358

src/language/lang_ms.php
Translation in Malay (Bahasa Melayu)
used the wrong branch "master" before.. #295
for issue #294
=> Add Malay translation

src/language/lang_ms.php
forgot to commit after pull & stash..
=> fix: forgot to commit the malay language changes after stash

src/language/lang_zh-tw.php, src/language/language.php
The reason why I modify a little code of language.php is to tell the difference when there are another Simplified Chinese translation.
Since I'm Taiwanese, I provide traditional chinese translation in this PR :)
=> Add Traditional Chinese translation & Modify a little code of language.php

extra/lib.sh
Fix for this https://github.com/facebook/fbctf/issues/386
=> Fix for incorrect hhvm.hhbc file path

.dockerignore
Fix https://github.com/facebook/fbctf/issues/403.
Best regards.
=> fix https://github.com/facebook/fbctf/issues/403

src/language/lang_sw.php
Add swahili language translation
=> Added swahili language transilation    

src/controllers/Controller.php, src/language/lang_fa.php
Platform was throwing error 500 and not even starting, this patch fixes the problem.
=> Fix the error 500 due to bad xhp

src/models/Attachment.php
* Set uploaded attachment permissions to 0600.
=> Force Attachment Permissions

src/controllers/modals/CountryModalController.php
* When scoring is disabled a message will now be displayed to the user when selecting a country.
* The input box for the country is disabled.
* The hint button is removed.
* The text of the submit button is changed to indicate that scoring is off and the button does not perform any action.
=> Disable Country Input When Scoring Disabled

src/controllers/AdminController.php, src/controllers/IndexController.php, src/models/Category.php
The category order in filter aren't ordered alphabetically
--
La lista de categorias en el filtro en el gameBoard, sale descolocada, y es más fácil para el ojo humano una lista ordenada alfabéticamente
=> Category order

src/controllers/IndexController.php
=> Fix autofocus for login form

src/controllers/AdminController.php, src/controllers/Controller.php, src/controllers/ajax/IndexAjaxController.php, src/models/Category.php
* Fixed a few HHVM/Hack typing and strict compliance issues.
* This is necessary before hh_client can run and be enforced during the build process. (See comments on #435)
* Updated formatting.
=> HHVM/Hack Typing Error Fixes

src/language/lang_hi.php
* Fixed minor syntax error due to character encoding.
* This will ensure the project builds (no Hack errors).
=> Fixed Syntax Errors in Hindi Language (Fixes Build Errors)

database/schema.sql, database/test_schema.sql, src/controllers/AdminController.php, src/controllers/Controller.php, src/controllers/GameboardController.php, src/controllers/IndexController.php, src/controllers/ViewModeController.php, src/controllers/ajax/AdminAjaxController.php, src/controllers/ajax/IndexAjaxController.php, src/language/lang_en.php, src/language/lang_es.php, src/models/Configuration.php, src/models/Logo.php, src/static/css/scss/_admin.scss, src/static/css/scss/_icons.scss, src/static/js/admin.js, src/static/js/fb-ctf.js, src/static/js/index.js, src/xhp/Custombranding.php, src/xhp/Fbbranding.php, tests/models/PasswordTypesTest.php
* This is a merge of the /dev and /master branch, including the new branding code and password complexity code, over top of the existing Live Sync API.
* This PR deconflicts the merge conflicts found between /dev and /master.
* Full commit logs for the /dev changes can be found in PR #448 and #442
=> Merge Deconflict of /dev and /master

src/language/lang_basque.php, src/language/lang_bp.php, src/language/lang_cat.php, src/language/lang_de.php, src/language/lang_es.php, src/language/lang_fa.php, src/language/lang_fr.php, src/language/lang_hi.php, src/language/lang_hu.php, src/language/lang_id.php, src/language/lang_it.php, src/language/lang_ms.php, src/language/lang_ru.php, src/language/lang_sv.php, src/language/lang_sw.php, src/language/lang_tr.php, src/language/lang_zh-tw.php
* All languages have been updated to include missing translations.
* Primarily this will declutter the error log, making debugging far easier.
=> Updated Language Translations

src/static/js/index.js
* Login form JavaScript now properly retrieves and renders errors when invalid login credentials are provided.
* Added teamLoginFormError() distinguished from teamNameFormError() and teamTokenFormError().
* Updated teamPasswordFormError() to read the login AJAX response and call the appropriate error function.
* This PR fixes the bug identified in Issue #521.
=> Fixed Login Form JS Bug (Fixes: #521)

src/controllers/AdminController.php, src/controllers/modals/ActionModalController.php, src/models/HintLog.php, src/models/Level.php, src/models/ScoreLog.php, src/static/js/admin.js
* Added deletion confirmation dialog when deleting levels.
* Level data is now deleted from HintLog, ScoresLog, and FailuresLog, when a level is deleted.
* Cache invalidation performed on level deletion for records containing levels.
=> Level Deletion Confirmation and Bug Fixes

README.md
* Updated links and information related to the installation process.
* Included a link to Quick Setup Guide.
=> Added Quick Setup Guide to README

CONTRIBUTING.md, README.md, extra/lib.sh, extra/provision.sh, package.json
* Remove NodeJS-Legacy (Fixes: #550) #551
* Updated version of node.js installed to fix critical provisioning errors. By default, Ubuntu 14.04 uses a legacy version of node.js. This code removes the legacy version and updates to a newer version.
* Source: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
* This PR fixes the provision/build issue from #550
* Downgraded DropkickJS and Streamlined Provision for NodeJS/Downloads (Fixes: #554) #555
* Downgraded Dropkick.js to version 2.1.10. The project originally was built using 2.1.10 and specified a near version in the 2.x.x release family. On August 27th 2017 Dropkick.js released version 2.2.0 which is incompatible with ES6 specs. The incompatibility with the new release of Dropkick.js caused the …
=> Merge #551, #555, #556, and #557

CONTRIBUTING.md, README.md, extra/lib.sh, extra/provision.sh, package.json, src/controllers/AdminController.php, src/language/lang_en.php, src/language/lang_es.php
I have rewritten a lot of spanish strings. 
In Spanish languague the first letter of each word is not in capital letters (except if you start a sentence).
Example: **"Password Types"**
* ~~'Politica de Contraseñas~~ (Incorrect)
* 'Politica de contraseñas' (Correct)
=> Spanish translations added

src/data/google_oauth.php
* The Google OAuth process now sets a CSRF token.
=> Google OAuth Security Update
